---
name: Reviewers

on:
  pull_request:
    types: [opened, reopened]
  push:
    paths:
      - .github/REVIEWERS

jobs:
  assign-reviewers:
    name: Assign
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Use REVIEWERS
        uses: ohnogumi/auto-reviewers@v0.0.5
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          config: ".github/REVIEWERS"
