---
name: Reviewers

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-reviewers:
    name: Assign
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Use REVIEWERS
        uses: fabasoad/reviewers-action@feat/v0
        with:
          reviewers-filename: "REVIEWERS"
