---
name: Reviewers

on:
  pull_request:
    types: [opened, reopened]
  push:
    paths:
      - .github/REVIEWERS
      - .github/workflows/assign-reviewers.yml

jobs:
  assign-reviewers:
    name: Assign
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Use REVIEWERS
        uses: zattoo/reviewers@4.1.0
        with:
          source: ".github/REVIEWERS"
