---
name: Unit Tests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - .github/workflows/unit-tests.yml
      - .tool-versions
      - vitest.config.ts
      - package.json
      - src/**
      - tsconfig.json
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  vitest:
    name: Vitest
    uses: fabasoad/reusable-workflows/.github/workflows/wf-js-unit-tests.yml@main
    permissions:
      contents: read
    secrets: inherit # pragma: allowlist secret
